# Generated by Django 5.0.7 on 2024-08-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart'),
        ('app', '0004_remove_cart_user_cart_product_cart_quantity'),
    ]

    operations = [
    ]
