# Generated by Django 5.0.7 on 2024-08-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20240826_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
